id: P3BE7CFB2
initial_creation_type: input
source_metadata:
  title: Mātṛcetra
  language: bo
  description: 'Texts by and about Mātṛcetra (blo gros bkra):'
  volume:
    50012e2210a84ef0b3953c07d60efd39:
      title: In Praise of the Three Jewels
      parent: Praise
created_at: '2022-03-01T02:17:21.048511'
last_modified_at: '2022-03-01T02:17:21.048514'
statistics:
  total_words: 210
  total_non_words: 10
quality:
  non_words_ratio: 0.05
